server:
    port: 8888

logging:
    file: spring.log

debug: true

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/autochess?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: 110120
        driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#        properties:
#            hibernate:
#                hbm2ddl:
#                    auto: update
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#                format_sql: true
#        show-sql: true
    devtools:
        restart:
            enabled: false   #热部署生效
            additional-paths: src/,resources/    #设置刷新目录
    freemarker:
        cache: false
    thymeleaf:
        cache: true
    http:
        log-request-details: true
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: -1
          max-wait: -1
          max-idle: 8
          min-idle: 0


mybatis:
    type-aliases-package: com.accenture.huaweigroup.module.entity
    mapper-locations: classpath:mapper/*.xml
